#ifndef __TAMISU_UAPI_SELINUX_H
#define __TAMISU_UAPI_SELINUX_H

#ifdef __cplusplus
extern "C" {
#endif // #ifdef __cplusplus

#ifdef __KERNEL__
#include <linux/types.h>
#endif // #ifdef __KERNEL__

#define TAMISU_SEPOLICY_CMD_NORMAL_PERM 1
#define TAMISU_SEPOLICY_CMD_XPERM 2
#define TAMISU_SEPOLICY_CMD_TYPE_STATE 3
#define TAMISU_SEPOLICY_CMD_TYPE 4
#define TAMISU_SEPOLICY_CMD_TYPE_ATTR 5
#define TAMISU_SEPOLICY_CMD_ATTR 6
#define TAMISU_SEPOLICY_CMD_TYPE_TRANSITION 7
#define TAMISU_SEPOLICY_CMD_TYPE_CHANGE 8
#define TAMISU_SEPOLICY_CMD_GENFSCON 9

#define TAMISU_SEPOLICY_SUBCMD_NORMAL_PERM_ALLOW 1
#define TAMISU_SEPOLICY_SUBCMD_NORMAL_PERM_DENY 2
#define TAMISU_SEPOLICY_SUBCMD_NORMAL_PERM_AUDITALLOW 3
#define TAMISU_SEPOLICY_SUBCMD_NORMAL_PERM_DONTAUDIT 4

#define TAMISU_SEPOLICY_SUBCMD_XPERM_ALLOW 1
#define TAMISU_SEPOLICY_SUBCMD_XPERM_AUDITALLOW 2
#define TAMISU_SEPOLICY_SUBCMD_XPERM_DONTAUDIT 3

#define TAMISU_SEPOLICY_SUBCMD_TYPE_STATE_PERMISSIVE 1
#define TAMISU_SEPOLICY_SUBCMD_TYPE_STATE_ENFORCE 2

#define TAMISU_SEPOLICY_SUBCMD_TYPE_CHANGE_CHANGE 1
#define TAMISU_SEPOLICY_SUBCMD_TYPE_CHANGE_MEMBER 2

#ifdef __cplusplus
}
#endif // #ifdef __cplusplus

#endif // #ifndef __TAMISU_UAPI_SELINUX_H
