tamisu-objs := tamisu_init.o
tamisu-objs += tamisu_feature.o

# TSR (Tracepoint Syscall Redirect) hook infrastructure
tamisu-objs += tamisu_syscall_event_bridge.o
tamisu-objs += tamisu_syscall_hook_manager.o
tamisu-objs += tamisu_lsm_hook.o
tamisu-objs += tamisu_tp_marker.o

ifeq ($(CONFIG_ARM64),y)
tamisu-objs += tamisu_patch_memory.o tamisu_syscall_hook.o
else
$(error "Tamisu only support aarch64")
endif
tamisu-objs += tamisu_setuid_hook.o
tamisu-objs += tamisu_dispatch.o
tamisu-objs += tamisu_perm.o
tamisu-objs += tamisu_supercall.o
tamisu-objs += tamisu_zygote_probe.o
tamisu-objs += tamisu_zygote_orch.o
tamisu-objs += tamisu_zygote_nl.o
tamisu-objs += tamisu_zygote_ctl.o
tamisu-objs += tamisu_symbol_resolver.o
tamisu-objs += tamisu_boot_event.o
tamisu-objs += tamisu_daemon_integration.o
tamisu-objs += tamisu_file_wrapper.o

tamisu-objs += tamisu_selinux.o
tamisu-objs += tamisu_sepolicy.o
tamisu-objs += tamisu_rules.o

obj-$(CONFIG_TAMISU) += tamisu.o

ifdef KBUILD_EXTMOD
ifeq ($(CONFIG_TAMISU_DEBUG),y)
ccflags-y += -DCONFIG_TAMISU_DEBUG=1
endif
endif

ccflags-y += -Wno-strict-prototypes
ccflags-y += -Wno-declaration-after-statement -Wno-unused-function -Wno-unused-variable -Wno-missing-braces
ccflags-y += -Wno-int-to-pointer-cast -Wno-declaration-after-statement

ccflags-y += -I$(srctree)/security/selinux -I$(srctree)/security/selinux/include
ccflags-y += -I$(objtree)/security/selinux -include $(srctree)/include/uapi/asm-generic/errno.h

ifeq ($(filter /%,$(src)),)
TAMISU_KERNEL_DIR := $(srctree)/$(src)
else
TAMISU_KERNEL_DIR := $(src)
endif

ccflags-y += -I$(TAMISU_KERNEL_DIR) -I$(TAMISU_KERNEL_DIR)/include

obj-$(CONFIG_TAMISU) += tamisu.o

KDIR := $(KDIR)
MDIR := $(realpath $(dir $(abspath $(lastword $(MAKEFILE_LIST)))))

ccflags-y += -DTAMISU_VERSION_STR='"$(shell date +%Y%m%d%H%M%S)"'

KERNEL_VERSION := $(VERSION).$(PATCHLEVEL)
KERNEL_TYPE := Non-GKI
# Check for GKI 2.0 (5.10+ or 6.x+)
ifneq ($(shell test \( $(VERSION) -ge 5 -a $(PATCHLEVEL) -ge 10 \) -o $(VERSION) -ge 6; echo $$?),0)
# Check for GKI 1.0 (5.4)
ifeq ($(shell test $(VERSION)-$(PATCHLEVEL) = 5-4; echo $$?),0)
KERNEL_TYPE := GKI 1.0
endif
else
KERNEL_TYPE := GKI 2.0
endif

# SELinux drivers check
ifeq ($(shell grep -q "current_sid(void)" $(srctree)/security/selinux/include/objsec.h; echo $$?),0)
ccflags-y += -DTAMISU_COMPAT_HAS_CURRENT_SID
endif
ifeq ($(shell grep -q "struct selinux_state " $(srctree)/security/selinux/include/security.h; echo $$?),0)
ccflags-y += -DTAMISU_COMPAT_HAS_SELINUX_STATE
endif

# Handle optional backports
ifeq ($(shell grep -q "strncpy_from_user_nofault" $(srctree)/include/linux/uaccess.h; echo $$?),0)
ccflags-y += -DTAMISU_OPTIONAL_STRNCPY
endif
ifeq ($(shell grep -q "ssize_t kernel_read" $(srctree)/fs/read_write.c; echo $$?),0)
ccflags-y += -DTAMISU_OPTIONAL_KERNEL_READ
endif
ifeq ($(shell grep "ssize_t kernel_write" $(srctree)/fs/read_write.c | grep -q "const void" ; echo $$?),0)
ccflags-y += -DTAMISU_OPTIONAL_KERNEL_WRITE
endif
ifeq ($(shell grep -q "int\s\+path_umount" $(srctree)/fs/namespace.c; echo $$?),0)
ccflags-y += -DTAMISU_HAS_PATH_UMOUNT
endif
ifeq ($(shell grep -q "inode_security_struct\s\+\*selinux_inode" $(srctree)/security/selinux/include/objsec.h; echo $$?),0)
ccflags-y += -DTAMISU_OPTIONAL_SELINUX_INODE
endif
ifeq ($(shell grep -q "task_security_struct\s\+\*selinux_cred" $(srctree)/security/selinux/include/objsec.h; echo $$?),0)
ccflags-y += -DTAMISU_OPTIONAL_SELINUX_CRED
endif
# seccomp_types.h were added on 6.7
ifeq ($(shell grep -q "atomic_t\s\+filter_count" $(srctree)/include/linux/seccomp.h $(srctree)/include/linux/seccomp_types.h; echo $$?),0)
ccflags-y += -DTAMISU_OPTIONAL_SECCOMP_FILTER_CNT
endif
# some old kernel backport this, let's check if put_seccomp_filter still exist
ifneq ($(shell grep -wq "put_seccomp_filter" $(srctree)/kernel/seccomp.c $(srctree)/include/linux/seccomp.h; echo $$?),0)
ccflags-y += -DTAMISU_OPTIONAL_SECCOMP_FILTER_RELEASE
endif
ifeq ($(shell grep -q "anon_inode_getfd_secure" $(srctree)/fs/anon_inodes.c; echo $$?),0)
ccflags-y += -DTAMISU_HAS_GETFD_SECURE
endif
ifeq ($(shell grep -A1 "^int vfs_getattr" $(srctree)/fs/stat.c | grep -q "query_flags"; echo $$?),0)
ccflags-y += -DTAMISU_HAS_NEW_VFS_GETATTR
endif
ifneq ($(shell grep -q __flush_dcache_area $(srctree)/arch/arm64/include/asm/cacheflush.h; echo $$?),0)
ccflags-y += -DTAMISU_HAS_NEW_DCACHE_FLUSH
endif

# Checks Samsung
ifeq ($(shell grep -q "CONFIG_KDP_CRED" $(srctree)/kernel/cred.c; echo $$?),0)
ccflags-y += -DSAMSUNG_UH_DRIVER_EXIST
endif
ifeq ($(shell grep -q "SEC_SELINUX_PORTING_COMMON" $(srctree)/security/selinux/avc.c; echo $$?),0)
ccflags-y += -DSAMSUNG_SELINUX_PORTING
endif
# Function proc_ops check
ifeq ($(shell grep -q "struct proc_ops " $(srctree)/include/linux/proc_fs.h; echo $$?),0)
ccflags-y += -DTAMISU_COMPAT_HAS_PROC_OPS
endif

ifdef TAMISU_MANAGER_PACKAGE
ccflags-y += -DTAMISU_MANAGER_PACKAGE=\"$(TAMISU_MANAGER_PACKAGE)\"
endif

# Keep a new line here!! Because someone may append config
