name: ClangFormat check

on:
  push:
    paths:
      - '.github/workflows/clang-format.yml'
      - 'core/**/*.c'
      - 'core/**/*.h'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/clang-format.yml'
      - 'core/**/*.c'
      - 'core/**/*.h'
      - 'core/.clang-format'

permissions:
  checks: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: check
        working-directory: core
        run: make check-format
