name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build-manager:
    uses: ./.github/workflows/build-manager.yml
    secrets: inherit
    with:
      full_archs: true
  release:
    needs:
      - build-manager
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7

      - name: Merge Manager APKs
        run: |
          mkdir -p Manager
          for dir in Manager-arm64-v8a Manager-x86_64 Manager-armv7; do
            if [ -d "$dir" ]; then
              find "$dir" -name "*.apk" -exec cp {} Manager/ \;
            fi
          done
          ls -la Manager/

      - name: Rename tamisu_daemon
        run: |
          mkdir -p tamisu_daemon
          for dir in ./tamisu_daemon-*; do
              if [ -d "$dir" ]; then
                 echo "----- Rename $dir -----"
                 tamisu_daemon_platform_name=$(basename "$dir")
                 find "$dir" -type f -name "tamisu_daemon" -path "*/release/*" | while read -r tamisu_daemon_file; do
                   if [ -f "$tamisu_daemon_file" ]; then
                     mv "$tamisu_daemon_file" "tamisu_daemon/$tamisu_daemon_platform_name"
                   fi
                 done
              fi
          done

      - name: Display structure of downloaded files
        run: ls -R

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Manager/*.apk
            android*-lkm/*.ko
            *-kasumi-lkm/*.ko
            tamisu_daemon/tamisu_daemon-*
